# Generated by Django 3.2.2 on 2022-07-26 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_publicaciones', '0002_auto_20220723_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_de_publicaciones.album'),
        ),
    ]
