# Generated by Django 3.2.2 on 2022-07-26 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_publicaciones', '0003_alter_publicacion_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='albums/images/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gestion_de_publicaciones.album')),
            ],
        ),
    ]
