# Generated by Django 3.2.2 on 2022-07-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_publicaciones', '0005_alter_publicacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
    ]
