# Generated by Django 3.2.2 on 2022-07-26 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_publicaciones', '0006_auto_20220726_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumimage',
            old_name='image',
            new_name='imagen',
        ),
    ]
